version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - pip install -r lambda_es_index/requirements.txt -t lambda_es_index
  post_build:
    commands:
      - echo Build completed on `date`
      - cd lambda_es_index
      - zip -r ../lambda_es_index.zip .
artifacts:
  files:
    - lambda_es_index.zip
    - Cloudformation.json