version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - echo Nothing to pre_build..
  build:
    commands:
      - pip install -r lambda_bundle/requirements.txt -t lambda_bundle
  post_build:
    commands:
      - echo packaging lambda `date`
      - cd lambda_bundle && zip -r ../lambda_bundle.zip . && cd ..
      - echo packaging webapp
      - mkdir tmp_webapp && cp -r webapp tmp_webapp
      
artifacts:
  files:
    - lambda_bundle.zip
    - Cloudformation.json
  base-directory: tmp_webapp
  