version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - pip install -r lambda_bundle/requirements.txt -t lambda_bundle
  post_build:
    commands:
      - echo Build completed on `date`
      - cd lambda_bundle
      - zip -r ../lambda_bundle.zip .
artifacts:
  files:
    - lambda_bundle.zip
    - Cloudformation.json