version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - echo Nothing to pre_build..
  build:
    commands:
      - pip install -r lambda_bundle/requirements.txt -t lambda_bundle
  post_build:
    commands:
      - echo creating package
      - mkdir buildoutput
      - ls
      - cd lambda_bundle && zip -r buildoutput/lambda_bundle.zip . && cd ..
      - echo packaging webapp
      - cp -r webapp buildoutput
      - cp  Cloudformation.json  buildoutput
      
artifacts:
  files: 
    - '**/*'
  base-directory: buildoutput

  