version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install zip
  pre_build:
    commands:
      - echo Nothing to pre_build..
  build:
    commands:
      - pip install -r lambda_bundle/requirements.txt -t lambda_bundle
  post_build:
    commands:
      - echo creating package
      - mkdir buildoutput
      - ls
      - cd lambda_bundle  && zip -r ../buildoutput/lambda_bundle.zip .  && cd ..
      - echo packaging webapp
      - cd webapp  && zip -r ../buildoutput/webapp.zip .  && cd .. 
      - cp Cloudformation.json  buildoutput
      - cp apigateway_lambda_sam.yaml  buildoutput
      - cp apigateway/swagger.yaml  buildoutput
artifacts:
  files: 
    - '**/*'
  base-directory: buildoutput

  