---
swagger: "2.0"
info:
  version: "2018-06-18T07:21:11Z"
  title: "RecommendationsApi"
host: "nw7dg8dnxa.execute-api.us-east-1.amazonaws.com"
basePath: "/TestIgnor"
schemes:
- "https"
paths:
  /recommend:
    post:
      produces:
      - "application/json"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
  /search:
    get:
      produces:
      - "application/json"
      parameters:
      - name: "movie"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
